spring.datasource.url=jdbc:mysql://192.168.10.138:13306/cordys-crm?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
spring.datasource.username=cordys-crm
spring.datasource.password=wNPBQwEe4QJGY67f


spring.data.redis.host=192.168.10.138

spring.data.redis.port=16379

spring.data.redis.password=redis_RDMHnR
spring.data.redis.database=7

spring.session.redis.repository-type=indexed

spring.session.timeout=43200s